#ifndef _BOARD_CONFIG_H_
#define _BOARD_CONFIG_H_

#include <driver/gpio.h>

#define AUDIO_INPUT_SAMPLE_RATE  16000
#define AUDIO_OUTPUT_SAMPLE_RATE 24000

#define AUDIO_I2S_METHOD_SIMPLEX

#ifdef AUDIO_I2S_METHOD_SIMPLEX

// No microphone on ESP32 — ASR-PRO handles wake word
#define AUDIO_I2S_MIC_GPIO_WS   GPIO_NUM_NC
#define AUDIO_I2S_MIC_GPIO_SCK  GPIO_NUM_NC
#define AUDIO_I2S_MIC_GPIO_DIN  GPIO_NUM_NC

// MAX98357 I2S speaker
#define AUDIO_I2S_SPK_GPIO_DOUT GPIO_NUM_5   // DIN
#define AUDIO_I2S_SPK_GPIO_BCLK GPIO_NUM_13  // BCLK
#define AUDIO_I2S_SPK_GPIO_LRCK GPIO_NUM_4   // LRC

#else

#define AUDIO_I2S_GPIO_WS   GPIO_NUM_4
#define AUDIO_I2S_GPIO_BCLK GPIO_NUM_13
#define AUDIO_I2S_GPIO_DIN  GPIO_NUM_NC
#define AUDIO_I2S_GPIO_DOUT GPIO_NUM_5

#endif

#define BOOT_BUTTON_GPIO        GPIO_NUM_0
#define ASR_BUTTON_GPIO         GPIO_NUM_NC   // ASR-PRO uses UART, not button
#define BUILTIN_LED_GPIO        GPIO_NUM_NC

// ASR-PRO UART pins
#define ASR_UART_RX_PIN         GPIO_NUM_16
#define ASR_UART_TX_PIN         GPIO_NUM_17

// GC9A01 240x240 Round Display SPI pins
#define DISPLAY_MOSI_PIN      GPIO_NUM_11  // SDA
#define DISPLAY_CLK_PIN       GPIO_NUM_12  // SCL
#define DISPLAY_CS_PIN        GPIO_NUM_10  // CS
#define DISPLAY_DC_PIN        GPIO_NUM_9   // DC
#define DISPLAY_RST_PIN       GPIO_NUM_8   // RST
#define DISPLAY_BACKLIGHT_PIN GPIO_NUM_NC  // BL hardwired to 3.3V

#ifdef CONFIG_LCD_GC9A01_240X240
#define LCD_TYPE_GC9A01_SERIAL
#define DISPLAY_WIDTH   240
#define DISPLAY_HEIGHT  240
#define DISPLAY_MIRROR_X true
#define DISPLAY_MIRROR_Y false
#define DISPLAY_SWAP_XY false
#define DISPLAY_INVERT_COLOR    true
#define DISPLAY_RGB_ORDER  LCD_RGB_ELEMENT_ORDER_BGR
#define DISPLAY_OFFSET_X  0
#define DISPLAY_OFFSET_Y  0
#define DISPLAY_BACKLIGHT_OUTPUT_INVERT false
#define DISPLAY_SPI_MODE 0
#endif

#endif // _BOARD_CONFIG_H_
