name: Build Custom Robot

on: [push, workflow_dispatch]

jobs:
  build:
    name: Build custom-robot
    runs-on: ubuntu-latest
    container:
      image: espressif/idf:v6.0.1
    steps:
      - uses: actions/checkout@v4
      - name: Build firmware
        shell: bash
        run: |
          source $IDF_PATH/export.sh
          python scripts/release.py custom-robot --name custom-robot
      - uses: actions/upload-artifact@v4
        with:
          name: custom-robot-firmware
          path: build/merged-binary.bin
          if-no-files-found: error
